import type { Metadata } from 'next';
import './globals.css';
import { TodoProvider } from '@/contexts/TodoContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased min-h-screen grid grid-rows-[auto_1fr_auto]">
        <TodoProvider>{children}</TodoProvider>
      </body>
    </html>
  );
}
